### PR TITLE
Remove Docker Build Items & Switch to GitHub Hosted Image

### PR DESCRIPTION
**Pull request by chris-leigh-dignifi**
We only utilize Snowflake in our dbt environment, so you can see I am only pulling from the Snowflake image. However, this can easily be modified to pull all dbt connectors. This eliminates the need to build and publish your own docker image to Docker Hub and updating this action to newer versions a breeze.

```
FROM ghcr.io/dbt-labs/dbt-core:1.6.0

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
```

### CODE REVIEW

**Comment by mwhitaker** [comment]
Thank you for that PR. As you mentioned, this is only for using the Snowflake image? We'll have to think about how to use the other connectors.

**Comment by chris-leigh-dignifi** [comment]
Correct! I believe if you switch to "FROM ghcr.io/dbt-labs/dbt-core:1.6.0" it will install all of the connectors.

**Comment by mwhitaker** [comment]
Awesome - will give that a try. Thanks again!

**Comment by mwhitaker** [comment]
I am going to close this for now as I don't think `FROM ghcr.io/dbt-labs/dbt-core:1.6.0` contains all adapters, it's just **dbt-core**.  I agree that dbt publishes images that include individual adapters, but I don't see an image for **dbt-all**.

For now I am just going to build versions following the guide here https://github.com/dbt-labs/dbt-core/tree/main/docker

**Pull request closed without merging**
